[mgr]
ratio = [1, 1, 2]
show_hidden = false
title_format = ""
tab_size = 2

[opener]
edit = [
  { run = "zed %S", orphan = true, desc = "Zed", for = "windows" },
  { run = "nvim %S", block = true, desc = "Neovim", for = "windows" },
  { run = "nvim %S", block = true, desc = "Neovim", for = "linux" },
]
