[mgr]
ratio = [1, 1, 2]
show_hidden = false
title_format = ""
tab_size = 2

[opener]
edit = [
  { run = "zed %s", orphan = true, desc = "Zed" },
  { run = "nvim %s", block = true, desc = "Neovim" },
]
