[mgr]
ratio = [1, 1, 2]
show_hidden = false
title_format = ""
tab_size = 2

[opener]
edit = [
  { run = "zed %*", orphan = true, desc = "Zed (file)", for = "windows" },
  { run = "zed .", orphan = true, desc = "Zed (folder)", for = "windows" },
  { run = "nvim %*", block = true, desc = "Neovim", for = "windows" },
]
